# Generated by Django 5.0.1 on 2024-01-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empID', models.CharField(max_length=100)),
                ('empName', models.CharField(max_length=50)),
                ('empEmail', models.CharField(max_length=50)),
                ('empAddress', models.CharField(max_length=50)),
                ('empPhone', models.CharField(max_length=50)),
            ],
        ),
    ]
